-- MySQL Script generated by MySQL Workbench
-- Thu Jul 24 20:03:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_creation` DATE NOT NULL,
  `utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_utilisateurs1_idx` (`utilisateurs_id` ASC) VISIBLE,
  CONSTRAINT `fk_contact_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` VARCHAR(350) NOT NULL,
  `date_envoie` DATE NOT NULL,
  `contact_id` INT NOT NULL,
  `utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_contact_idx` (`contact_id` ASC) VISIBLE,
  INDEX `fk_message_utilisateurs1_idx` (`utilisateurs_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `mydb`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `adresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vehicule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vehicule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(45) NOT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  `agence_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicule_agence1_idx` (`agence_id` ASC) VISIBLE,
  CONSTRAINT `fk_vehicule_agence1`
    FOREIGN KEY (`agence_id`)
    REFERENCES `mydb`.`agence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  `vehicule_id` INT NOT NULL,
  `utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Location_vehicule1_idx` (`vehicule_id` ASC) VISIBLE,
  INDEX `fk_Location_utilisateurs1_idx` (`utilisateurs_id` ASC) VISIBLE,
  CONSTRAINT `fk_Location_vehicule1`
    FOREIGN KEY (`vehicule_id`)
    REFERENCES `mydb`.`vehicule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Location_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paiement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `statut` VARCHAR(10) NULL,
  `montant` FLOAT NOT NULL,
  `Location_id` INT NOT NULL,
  `utilisateurs_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_paiement_Location1_idx` (`Location_id` ASC) VISIBLE,
  INDEX `fk_paiement_utilisateurs1_idx` (`utilisateurs_id` ASC) VISIBLE,
  CONSTRAINT `fk_paiement_Location1`
    FOREIGN KEY (`Location_id`)
    REFERENCES `mydb`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paiement_utilisateurs1`
    FOREIGN KEY (`utilisateurs_id`)
    REFERENCES `mydb`.`utilisateurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
